name: gluestack_ui
description: "A new Flutter plugin project."
version: 0.0.1
homepage: https://github.com/gluestack/gluestack-flutter
repository: https://github.com/gluestack/gluestack-flutter
issue_tracker: https://github.com/gluestack/gluestack-flutter/issues

environment:
  sdk: ">=3.2.1 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

  fluttertoast: ^8.2.4
  provider: ^6.1.1
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

# TODO: Add relevent screenshot to show in pub.dev listing.
screenshots:

# Add upto 5 topics to get indexed better on pub.dev
topics:
  - ui
