name: gluestack_ui
description: "Universal Themed & Unstyled Widgets for Flutter"

homepage: https://github.com/gluestack/gluestack-flutter
repository: https://github.com/gluestack/gluestack-flutter
issue_tracker: https://github.com/gluestack/gluestack-flutter/issues
documentation: https://github.com/gluestack/gluestack-flutter

version: 0.0.1-alpha.2

environment:
  sdk: ">=3.2.1 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

  fluttertoast: ^8.2.4
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

# TODO: Add relevent icon or screenshot to show in pub.dev listing.
screenshots:

# Add upto 5 topics to get indexed better on pub.dev
topics:
  - ui
  - widgets
  - design-system
  - ui-library
